version: "3.9"
services:
  mongo:
    image: "mongo:5.0.9"
    volumes:
      - .data/mongo:/data/db
  webapp:
    build: .
    depends_on:
      - "mongo"
    environment:
      - MongoDB_URI=mongodb://taskmanagementservice_mongo_1:27017
    ports:
      - "8080:8080"