version: "3.9"
services:
  mongo:
    image: "mongo:5.0.9"
    container_name: taskmanagementservice_mongodb
    volumes:
      - .data/mongo:/data/db
  webapp:
    build: .
    container_name: taskmanagementservice_api
    depends_on:
      - "mongo"
    environment:
      - MongoDB_URI=mongodb://taskmanagementservice_mongodb:27017
    ports:
      - "8080:8080"